import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/googlelogin">GoogleLogin</Link>
        </li>
        <li>
          <Link to="/productrecommendationengine">
            ProductRecommendationEngine
          </Link>
        </li>
        <li>
          <Link to="/smartcategorisation">SmartCategorisation</Link>
        </li>
        <li>
          <Link to="/pricingengine">PricingEngine</Link>
        </li>
        <li>
          <Link to="/videolibrary">VideoLibrary</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
